[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd rentevent-server && pnpm install"]

[phases.build]
cmds = ["cd rentevent-server && pnpm run build"]

[start]
cmd = "cd rentevent-server && pnpm run start"
